log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.Target=System.out
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%m%n
log4j.appender.console.layout.charset = SJIS

log4j.appender.action=org.apache.log4j.RollingFileAppender
log4j.appender.action.File=C:\\lacs\\lease\\LACS\\log_online\\action.log
log4j.appender.action.Append=true
log4j.appender.action.MaxFileSize=500KB
log4j.appender.action.MaxBackupIndex=3
log4j.appender.action.layout=org.apache.log4j.PatternLayout
log4j.appender.action.layout.ConversionPattern=%m%n
log4j.appender.action.layout.charset = SJIS

log4j.appender.common=org.apache.log4j.RollingFileAppender
log4j.appender.common.File=C:\\lacs\\lease\\LACS\\log_online\\common.log
log4j.appender.common.Append=true
log4j.appender.common.MaxFileSize=500KB
log4j.appender.common.MaxBackupIndex=3
log4j.appender.common.layout=org.apache.log4j.PatternLayout
log4j.appender.common.layout.ConversionPattern=%m%n
log4j.appender.common.layout.charset = SJIS

log4j.rootCategory=error, console
log4j.logger.jp.co.pro_app.lacs.common.log.LACSTraceLog=error, common
log4j.logger.jp.co.pro_app.lacs.common.log.LACSActionLog=info, action
