#
# Field Internal Padding Setting
#
default.field.padding.top=2.0
default.field.padding.left=2.0
default.field.padding.bottom=2.0
default.field.padding.right=2.0
#
# Font Setting
#
default.font.name=Helvetica
default.font.size=14.0
#
# Text Position
#
default.text.character.space=0.0
default.text.word.space=0.0
default.text.horizontal.scale=100.0
#
# Encoding Setting
#
default.cjk.encoding.name=UniJIS-UCS2-H
default.latin.encoding.name=WinAnsiEncoding
default.private.encoding.name=UniJIS-UCS2-H
#
# For MSGothic Font
#
font.MSGothic.latin=MS-Gothic
font.MSGothic.cjk=MS-Gothic
font.MSGothic.private=MS-Gothic
