font.root.dir=fonts
code2cid.root.dir=code2cid
std.report.conf.root.dir=resources
default.report.config.file=report.properties
font.embedded.tabToSpace=4
font.truetype.cache.enabled=true
font.truetype.cache.interval=6
font.truetype.cache.capacity=0
font.truetype.cache.sweep.limits=16
font.type0.cache.enabled=true
font.type0.cache.interval=6
font.type0.cache.capacity=0
font.type0.cache.sweep.limits=16
font.type2.cache.enabled=true
font.type2.cache.interval=6
font.type2.cache.capacity=0
font.type2.cache.sweep.limits=16
report.cache.enabled=true
report.cache.capacity=64
report.cache.interval=30
report.cache.sweep.limits=8
Adobe-Japan1-4.glyph.width=231 325 500 326 389 500 631 631 500
Adobe-Identity-0.glyph.width=
default.encoding.name=UniJIS-UCS2-H
